CREATE TABLE "accounts" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "customer_id" BIGSERIAL NOT NULL REFERENCES customers(id),
  "email" VARCHAR(255) NOT NULL CONSTRAINT "unique_accounts_email" UNIQUE,
  "password" VARCHAR(255) NOT NULL,
  "type" VARCHAR(255) NOT NULL,
  "balance" NUMERIC(10, 2) NOT NULL DEFAULT 0,
  "created_at" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);