runtime: nodejs
env: flex

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '20'

manual_scaling:
  instances: 1

env_variables:
  NODE_ENV: ''
  JWT_SECRET: ''
  JWT_EXPIRED: ''
  SESSION_SECRET: ''
  DATABASE_URL: ''
  IMAGEKIT_PUBLIC_KEY: ''
  IMAGEKIT_PRIVATE_KEY: ''
  IMAGEKIT_URL_ENDPOINT: ''
  GOOGLE_NODE_RUN_SCRIPTS: ''

beta_settings:
  cloud_sql_instances: euphoric-world-440804-k1:asia-southeast1:db-pg-bejskm7
