runtime: nodejs
env: flex

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '20'

manual_scaling:
  instances: 1

env_variables:
  DATABASE_URL: '${{ secrets.DATABASE_URL }}'
  IMAGEKIT_PRIVATE_KEY: '${{ secrets.IMAGEKIT_PRIVATE_KEY }}'
  IMAGEKIT_PUBLIC_KEY: '${{ secrets.IMAGEKIT_PUBLIC_KEY }}'
  IMAGEKIT_URL_ENDPOINT: '${{ secrets.IMAGEKIT_URL_ENDPOINT }}'
  JWT_EXPIRED: '${{ secrets.JWT_EXPIRED }}'
  JWT_SECRET: '${{ secrets.JWT_SECRET }}'
  NODE_ENV: '${{ secrets.NODE_ENV }}'
  SESSION_SECRET: '${{ secrets.SESSION_SECRET }}'

beta_settings:
  cloud_sql_instances: '${{ secrets.CLOUD_SQL_INSTANCE }}'
