name: Deploy to Google App Engine (GAE)

on:
  workflow_run:
    workflows: ['🔎 CI Checks']
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Set up Cloud SQL instance variable
        env:
          CLOUD_SQL_INSTANCE: ${{ secrets.CLOUD_SQL_INSTANCE }}
        run: |
          echo "beta_settings:" >> app.yaml
          echo "  cloud_sql_instances: '$CLOUD_SQL_INSTANCE'" >> app.yaml

      - name: Create env.yaml with Secrets
        run: |
          touch env.yaml
          echo "env_variables:" >> env.yaml
          echo "  DATABASE_URL: '${{ secrets.DATABASE_URL }}'" >> env.yaml
          echo "  IMAGEKIT_PRIVATE_KEY: '${{ secrets.IMAGEKIT_PRIVATE_KEY }}'" >> env.yaml
          echo "  IMAGEKIT_PUBLIC_KEY: '${{ secrets.IMAGEKIT_PUBLIC_KEY }}'" >> env.yaml
          echo "  IMAGEKIT_URL_ENDPOINT: '${{ secrets.IMAGEKIT_URL_ENDPOINT }}'" >> env.yaml
          echo "  JWT_EXPIRED: '${{ secrets.JWT_EXPIRED }}'" >> env.yaml
          echo "  JWT_SECRET: '${{ secrets.JWT_SECRET }}'" >> env.yaml
          echo "  NODE_ENV: '${{ secrets.NODE_ENV }}'" >> env.yaml
          echo "  APP_EMAIL: '${{ secrets.APP_EMAIL }}'" >> env.yaml
          echo "  APP_PASS: '${{ secrets.APP_PASS }}'" >> env.yaml
          echo "  SESSION_SECRET: '${{ secrets.SESSION_SECRET }}'" >> env.yaml
          echo "  GOOGLE_OAUTH_CLIENT_SECRET: '${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}'" >> env.yaml
          echo "  GOOGLE_OAUTH_CLIENT_ID: '${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}'" >> env.yaml
          echo "  GOOGLE_OAUTH_CALLBACK_URL: '${{ secrets.GOOGLE_OAUTH_CALLBACK_URL }}'" >> env.yaml
          echo "  SENTRY_AUTH_TOKEN: '${{ secrets.SENTRY_AUTH_TOKEN}}'" >> env.yaml
          echo "  SENTRY_DSN: '${{ secrets.SENTRY_DSN}}'" >> env.yaml

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy

      - name: Clean up files
        run: rm app.yaml env.yaml
