name: Deploy to Google App Engine (GAE)

on:
  workflow_run:
    workflows: ['🔎 CI Checks'] # Name of the workflow from main.yml
    types:
      - completed
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only runs if main.yml is successful
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Google App Engine
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          IMAGEKIT_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
          IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
          IMAGEKIT_URL_ENDPOINT: ${{ secrets.IMAGEKIT_URL_ENDPOINT }}
          JWT_EXPIRED: ${{ secrets.JWT_EXPIRED }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        run: |
          gcloud app deploy app.yaml --quiet \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }},IMAGEKIT_PRIVATE_KEY=${{ secrets.IMAGEKIT_PRIVATE_KEY }},IMAGEKIT_PUBLIC_KEY=${{ secrets.IMAGEKIT_PUBLIC_KEY }},IMAGEKIT_URL_ENDPOINT=${{ secrets.IMAGEKIT_URL_ENDPOINT }},JWT_EXPIRED=${{ secrets.JWT_EXPIRED }},JWT_SECRET=${{ secrets.JWT_SECRET }},NODE_ENV=${{ secrets.NODE_ENV }},SESSION_SECRET=${{ secrets.SESSION_SECRET }}"
